config/routes.rb
Rails.application.routes.draw do

  resources :properties do
    collection do 
      get 'search'
      get 'page/:page' => 'properties#paginate', as: :page
      get 'my_properties' => 'properties#my_properties', as: :my_properties
    end  
    member do
      post 'add_customer'
      get 'remove_customer/:customer_id' => 'properties#remove_customer', as: :remove_customer
    end
  end

  resources :agents do
    collection do 
      get 'search'
      get 'page/:page' => 'agents#paginate', as: :page
    end  
  end  

  resources :customers do
    collection do 
      get 'search'
      get 'page/:page' => 'customers#paginate', as: :page
    end  
  end  

  resources :states do
    collection do 
      get 'search'
      get 'page/:page' => 'states#paginate', as: :page
    end  
  end  

  resources :users do
    collection do 
      get 'search'
      get 'page/:page' => 'users#paginate', as: :page
    end  
  end  

  root 'sessions#index'

  get 'login' => 'sessions#index'
  get 'sessions/forgot_password'
  post 'sessions/create'
  delete 'sessions/destroy'
  get 'dashboard' => 'dashboard#index'

  get 'my_account', to: 'my_account#show'
  put 'my_account', to: 'my_account#update'
  patch 'my_account', to: 'my_account#update'

end

app/models/state.rb
class State < ActiveRecord::Base

  validates :code, presence: true, uniqueness: { case_sensitive: false }
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def self.paginate(page=1)
    page ||= 1

    # Set the pagination info on every data pull
    total_record_count = State.count
    pages  = (total_record_count.to_f / ENV['MAX_RECORDS_PER_PAGE'].to_f).ceil
    current_page = page

    max_records_per_page = ENV['MAX_RECORDS_PER_PAGE'].to_i
    current_offset = ((page.to_i*max_records_per_page))-max_records_per_page
    states = State.limit(max_records_per_page).offset(current_offset)
    current_record_count = states.try(:count)

    {
      current_page: page,
      pages: pages,
      max_records_per_page: max_records_per_page,
      current_offset: current_offset,
      current_record_count: current_record_count,
      total_record_count: total_record_count,
      records: states

    }
  end

  def self.search(search_criteria, page=1)
    page ||= 1

    # Set the pagination info on every data pull
    total_record_count = State.where(" code LIKE LOWER('%#{search_criteria}%') OR name LIKE LOWER('%#{search_criteria}%') ").count
    pages  = (total_record_count.to_f / ENV['MAX_RECORDS_PER_PAGE'].to_f).ceil
    current_page = page

    max_records_per_page = ENV['MAX_RECORDS_PER_PAGE'].to_i
    current_offset = ((page.to_i*max_records_per_page))-max_records_per_page
    states = State.where(" code LIKE LOWER('%#{search_criteria}%') OR name LIKE LOWER('%#{search_criteria}%') ").limit(max_records_per_page).offset(current_offset)
    current_record_count = states.try(:count)

    {
      current_page: page,
      pages: pages,
      max_records_per_page: max_records_per_page,
      current_offset: current_offset,
      current_record_count: current_record_count,
      total_record_count: total_record_count,
      records: states
    }
  end   

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @page_title = "States List"
    state_data = State::paginate
    set_pagination(state_data)
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @page_title = "State Details"
  end

  # GET /states/new
  def new
    @page_title = "New State"
    @state = State.new
  end

  # GET /states/1/edit
  def edit
    @page_title = "Edit State"
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        flash[:type] = FLASH_TYPES[:success]
        flash[:msg] = "State successfully created"          
        format.html { redirect_to @state}
        format.json { render :show, status: :created, location: @state }
      else
        flash.now[:type] = FLASH_TYPES[:warning]
        flash.now[:msg] = "Please fill in all required information"         
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        flash[:type] = FLASH_TYPES[:success]
        flash[:msg] = "State successfully updated"        
        format.html { redirect_to @state }
        format.json { render :show, status: :ok, location: @state }
      else
        flash.now[:type] = FLASH_TYPES[:warning]
        flash.now[:msg] = "Please fill in all required information"             
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    if @state.destroy
      respond_to do |format|
        flash.now[:type] = FLASH_TYPES[:success]
        flash.now[:msg] = "State successfully deleted"
        format.html { redirect_to states_url }
        format.json { head :no_content }
      end
    else
        flash.now[:type] = FLASH_TYPES[:warning]
        flash.now[:msg] = "There was a problem trying to delete the state"     
        format.html { render :index }
        format.json { render json: @state.errors, status: :unprocessable_entity }      
    end
  end

  def search 
    current_page = params[:page]
    search_criteria = params[:search_criteria]
    state_data = State.search(search_criteria, current_page)
    set_pagination(state_data)
    flash.now[:search_criteria] = params[:search_criteria]

    if state_data[:total_record_count] > 0
      flash.now[:type] = FLASH_TYPES[:info]
      flash.now[:msg] = "#{state_data[:total_record_count]} results found"
    else
      flash.now[:type] = FLASH_TYPES[:warning]
      flash.now[:msg] = "No records found matching your criteria"
    end


    respond_to  do |format| 
      format.html { render :index }
      format.json { head :no_content }
    end
  end

  def paginate
    current_page = params[:page]
    state_data = State.paginate(current_page)
    set_pagination(state_data)

    respond_to  do |format| 
      format.html { render :index }
      format.json { head :no_content }
    end   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :code)
    end

    def set_pagination(state_data)
      @states = state_data[:records]
      @total_record_count = state_data[:total_record_count]
      @pages = state_data[:pages]
      @current_record_count = state_data[:current_record_count]
    end     
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_edit.html.erb
<%= render 'form' %>

<%= link_to "Back", states_path %>

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <div class="form-group">
    <%= f.label :code, "Code" %><br>
    <%= f.text_field :code, class: "form-control" %>
    <% if @state.errors.has_key?(:code) %>
      <span class="field-error"><%= @state.errors.messages[:code].join(", ") %></span>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :name, "Title" %><br>
    <%= f.text_field :name, class: "form-control" %>
    <% if @state.errors.has_key?(:name) %>
      <span class="field-error"><%= @state.errors.messages[:name].join(", ") %></span>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/states/edit.html.erb
<%= render 'edit' %>

app/views/states/index.html.erb
<!-- SEARCH BAR -->
<div class="row summary">
  <div class="col-md-12">
  <%= form_tag search_states_path, method: "get" do %>
    <div class="form-group">
      <div class="input-group">
        <%= text_field_tag "search_criteria", flash[:search_criteria], placeholder: "code or name...", class: "form-control" %>
        <span class="input-group-btn">
        <%= button_tag type: "submit", class: "btn btn-default", id: "search_btn"  do %>
          <span class="glyphicon glyphicon-search"></span> search
        <% end %>
        </span>
      </div>
    </div>
  <% end %>
  </div>   
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-responsive">
      <thead>
        <tr>
          <th class="text-center">Code</th>
          <th class="text-center">Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @states.each do |state| %>
          <tr>
            <td class="text-left"><%= state.code %></td>
            <td class="text-center"><%= state.name %></td>
            <td class="text-center"><%= link_to 'Details', state %></td>
            <td class="text-center"><%= link_to 'Edit', edit_state_path(state) %></td>
            <td class="text-center"><%= link_to 'Delete', state, method: :delete, data: { confirm: 'Are you sure you want to delete this state?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <span style="font-style: italic">Showing <strong><%= @current_record_count %></strong> records of <strong><%= @total_record_count %></strong></span>
  </div>
  <div class="col-md-4">
    <%= link_to 'New State', new_state_path, class: "pull-right btn btn-primary" %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <nav>
      <ul class="pagination">
        <li class="disabled">
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <% 1.upto(@pages) do |page| %>
          <% if flash[:search_criteria] %>
            <li><%= link_to page, search_states_path(search_criteria: flash[:search_criteria] , page: page) %></li>
          <% else %>
            <li><%= link_to page, page_states_path(page) %></li>
          <% end %>
        <% end %>
        <li>
          <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>  
  </div>
</div>

app/views/states/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<%= render 'edit' %>