config/routes.rb
Rails.application.routes.draw do

  resources :properties do
    collection do 
      get 'search'
      get 'page/:page' => 'properties#paginate', as: :page
      get 'my_properties' => 'properties#my_properties', as: :my_properties
    end  
    member do
      post 'add_customer'
      get 'remove_customer/:customer_id' => 'properties#remove_customer', as: :remove_customer
    end
  end

  resources :agents do
    collection do 
      get 'search'
      get 'page/:page' => 'agents#paginate', as: :page
    end  
  end  

  resources :customers do
    collection do 
      get 'search'
      get 'page/:page' => 'customers#paginate', as: :page
    end  
  end  

  resources :states do
    collection do 
      get 'search'
      get 'page/:page' => 'states#paginate', as: :page
    end  
  end  

  resources :users do
    collection do 
      get 'search'
      get 'page/:page' => 'users#paginate', as: :page
    end  
  end  

  root 'sessions#index'

  get 'login' => 'sessions#index'
  get 'sessions/forgot_password'
  post 'sessions/create'
  delete 'sessions/destroy'
  get 'dashboard' => 'dashboard#index'

  get 'my_account', to: 'my_account#show'
  put 'my_account', to: 'my_account#update'
  patch 'my_account', to: 'my_account#update'

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :state
  belongs_to :agent
  before_destroy :delete_photo
  before_save :save_photo
  has_many :customer_properties
  has_many :customers, through: :customer_properties

  enum status: [:for_sale, :sold]

  validates :title, presence: true
  validates :description, presence: true
  validates :price, numericality: { greater_than: 0 } 
  validates :street_name, presence: true
  validates :street_number, presence: true
  validates :city, presence: true
  validates :zipcode, presence: true
  validates :state, presence: true
  validates :status, presence: true
  validates :agent, presence: true

  def address
    [street_number, street_name, suite].join(' ')
  end

  def full_address
    "#{street_number} #{street_name} #{city} #{state.code} #{zipcode}"
  end

  def location
    "#{city}, #{state.code}, #{zipcode}"
  end  

  def self.paginate(page=1)
    page ||= 1

    # Set the pagination info on every data pull
    total_record_count = Property.count
    pages  = (total_record_count.to_f / ENV['MAX_RECORDS_PER_PAGE'].to_f).ceil
    current_page = page

    max_records_per_page = ENV['MAX_RECORDS_PER_PAGE'].to_i
    current_offset = ((page.to_i*max_records_per_page))-max_records_per_page
    properties = Property.limit(max_records_per_page).offset(current_offset)
    current_record_count = properties.try(:count)

    {
      current_page: page,
      pages: pages,
      max_records_per_page: max_records_per_page,
      current_offset: current_offset,
      current_record_count: current_record_count,
      total_record_count: total_record_count,
      records: properties

    }
  end

  def self.search(search_criteria, page=1)
    page ||= 1

    # Set the pagination info on every data pull
    total_record_count = Property.where(" title LIKE LOWER('%#{search_criteria}%') OR description LIKE LOWER('%#{search_criteria}%') ").count
    pages  = (total_record_count.to_f / ENV['MAX_RECORDS_PER_PAGE'].to_f).ceil
    current_page = page

    max_records_per_page = ENV['MAX_RECORDS_PER_PAGE'].to_i
    current_offset = ((page.to_i*max_records_per_page))-max_records_per_page
    properties = Property.where(" title LIKE LOWER('%#{search_criteria}%') OR description LIKE LOWER('%#{search_criteria}%') ").limit(max_records_per_page).offset(current_offset)
    current_record_count = properties.try(:count)

    {
      current_page: page,
      pages: pages,
      max_records_per_page: max_records_per_page,
      current_offset: current_offset,
      current_record_count: current_record_count,
      total_record_count: total_record_count,
      records: properties
    }
  end

  def self.to_csv
    attributes = %w{id title photo price street_number street_name suite zipcode city state_id agent_id status created_at updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |property|
        csv << attributes.map{ |attr| property.send(attr) }
      end
    end
  end

  private
    def delete_photo
      if photo
        File::delete(Rails.root.join('public', 'uploads', photo))
      end
    end  

    def save_photo
      if photo_changed?
        FileUtils::mv(Rails.root.join('tmp', photo), Rails.root.join('public', 'uploads', photo))
      end
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy, :add_customer, :remove_customer]
  before_action :load_states, only: [:show, :edit, :new, :create, :update, :add_customer, :remove_customer]
  before_action :load_agents, only: [:show, :edit, :new, :create, :update, :add_customer, :remove_customer]
  before_action :load_customers, only: [:show, :edit, :new, :create, :update, :add_customer, :remove_customer]
  before_action :upload_photo, only: [:create, :update]
  before_action :load_my_properties, only: [:my_properties]

  # GET /properties
  # GET /properties.json
  def index
    @page_title = "Property List"
    property_data = Property::paginate
    set_pagination(property_data)

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @properties, status: :ok }
      format.csv { send_data Property.to_csv, filename: "properties-#{Date.today}.csv" }
      format.pdf do
        pdf = Prawn::Document.new
        pdf.text(Property.to_csv)
        pdf.render_file(Rails.root.join('tmp', "properties-#{Date.today}.pdf"))
        send_file Rails.root.join('tmp', "properties-#{Date.today}.pdf")
      end
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @page_title = "Property Details"
  end

  # GET /properties/new
  def new
    @page_title = "New Property"
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
    @page_title = "Edit Property"
  end

  # POST /properties
  # POST /properties.json
  def create
    @page_title = "New Property"
    @property = Property.new(property_params)
    respond_to do |format|
      if @property.save
        flash[:type] = FLASH_TYPES[:success]
        flash[:msg] = "Property successfully created"       
        format.html { redirect_to @property }
        format.json { render :show, status: :created, location: @property }
      else
        flash.now[:type] = FLASH_TYPES[:warning]
        flash.now[:msg] = "Please fill in all required information"         
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        flash[:type] = FLASH_TYPES[:success]
        flash[:msg] = "Property successfully updated"          
        format.html { redirect_to @property}
        format.json { render :show, status: :ok, location: @property }
      else
        flash.now[:type] = FLASH_TYPES[:warning]
        flash.now[:msg] = "Please fill in all required information"     
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    if @property.destroy
      respond_to do |format|
        flash[:type] = FLASH_TYPES[:success]
        flash[:msg] = "Property successfully deleted"
        format.html { redirect_to properties_url }
        format.json { head :no_content }
      end
    else
        flash.now[:type] = FLASH_TYPES[:warning]
        flash.now[:msg] = "There was a problem trying to delete the property"     
        format.html { render :index }
        format.json { render json: @property.errors, status: :unprocessable_entity }      
    end
  end

  def search 
    current_page = params[:page]
    search_criteria = params[:search_criteria]
    property_data = Property.search(search_criteria, current_page)
    set_pagination(property_data)
    flash.now[:search_criteria] = params[:search_criteria]

    if property_data[:total_record_count] > 0
      flash.now[:type] = FLASH_TYPES[:info]
      flash.now[:msg] = "#{property_data[:total_record_count]} results found"
    else
      flash.now[:type] = FLASH_TYPES[:warning]
      flash.now[:msg] = "No records found matching your criteria"
    end


    respond_to  do |format| 
      format.html { render :index }
      format.json { head :no_content }
    end
  end

  def paginate
    current_page = params[:page]
    property_data = Property.paginate(current_page)
    set_pagination(property_data)

    respond_to  do |format| 
      format.html { render :index }
      format.json { head :no_content }
    end   
  end

  def add_customer
    if params[:customer_id]
      @property.customers << Customer.find(params[:customer_id])
      flash[:type] = FLASH_TYPES[:info]
      flash[:msg] = "Customer successfully added"
    else
      flash.now[:type] = FLASH_TYPES[:warning]
      flash.now[:msg] = "No customer selected"
    end


    respond_to  do |format| 
      format.html { redirect_to @property }
      format.json { head :no_content }
    end    
  end

  def remove_customer
    if params[:customer_id]
      @property.customer_properties.where(customer_id: params[:customer_id]).first.destroy
      flash[:type] = FLASH_TYPES[:info]
      flash[:msg] = "Customer successfully removed"
    else
      flash.now[:type] = FLASH_TYPES[:warning]
      flash.now[:msg] = "No customer selected"
    end


    respond_to  do |format| 
      format.html { redirect_to @property }
      format.json { head :no_content }
    end    
  end

  def my_properties
    @page_title = "My Properties"
    respond_to  do |format| 
      format.html { render :my_properties }
      format.json { render json: @my_properties, status: :ok }
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:title, :description, :photo, :price, :street_number, :street_name, :suite, :zipcode, :city, :state_id, :agent_id, :status)
    end

    def set_pagination(property_data)
      @properties = property_data[:records]
      @total_record_count = property_data[:total_record_count]
      @pages = property_data[:pages]
      @current_record_count = property_data[:current_record_count]
    end  

    def load_states
      @states = State.all
    end

    def load_agents
      @agents = Agent.all
    end

    def load_customers
      if @property
        @leads = Customer.joins(:user).where.not(id: Property.find(params[:id]).customers.ids).pluck("CONCAT(users.first_name,' ' ,users.last_name)", "customers.id")
        @customers = Customer.joins(:user).where(id: Property.find(params[:id]).customers.ids).pluck("CONCAT(users.first_name,' ' ,users.last_name)", "customers.id")
      else
        @leads = Customer.joins(:user).pluck("CONCAT(users.first_name,' ' ,users.last_name)", "customers.id")
        @customers = []
      end
    end

    def load_my_properties
      @customer = Customer.find_by(user_id: @current_user.id)
      @my_properties = @customer.properties
    end

    def upload_photo
      uploaded_io = params[:property][:photo_file]
      return unless uploaded_io
      begin
        photo_filename = "#{SecureRandom::uuid}#{File::extname(uploaded_io.original_filename)}"
        File.open(Rails.root.join('tmp', photo_filename), 'wb') do |file|
          file.write(uploaded_io.read)
        end
        @property.photo = photo_filename
      rescue StandardError => e
        raise StandardError.new "There was an internal error trying to upload the photo: #{e.message}"
      end

    end      
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_edit.html.erb
<%= render 'form' %>

<%= link_to "Back", properties_path %>

app/views/properties/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for(@property) do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title" %><br>
        <%= f.text_field :title, class: "form-control" %>
        <% if @property.errors.has_key?(:title) %>
          <span class="field-error"><%= @property.errors.messages[:title].join(", ") %></span>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :description, "Description" %><br>
        <%= f.text_area :description, class: "form-control" %>
        <% if @property.errors.has_key?(:description) %>
          <span class="field-error"><%= @property.errors.messages[:description].join(", ") %></span>
        <% end %>
      </div>  

      <div class="form-group">
      <% if @property.photo %>
        <div>
          <%= image_tag("/uploads/#{@property.photo}", size: "600x400", alt: "Photo") %>
        </div>
      <% end %>
        <%= f.label :photo_file, "Photo" %><br>
        <%= f.file_field :photo_file, class: "form-control" %>
        <% if @property.errors.has_key?(:photo) %>
          <span class="field-error"><%= @property.errors.messages[:photo].join(", ") %></span>
        <% end %>
      </div>  

      <div class="form-group">
        <%= f.label :agent, "Agent" %><br>
        <%= f.collection_select :agent_id, @agents, :id, :full_name, { include_blank: true }, { class: "form-control" } %>    
        <% if @property.errors.has_key?(:agent) %>
          <span class="field-error"><%= @property.errors.messages[:agent].join(", ") %></span>
        <% end %>      
      </div>

      <div class="form-group">
        <%= f.label :status, "Status" %><br>
        <%= f.select :status, Property.statuses.to_a.map { |s| [s[0].humanize, s[0]] }, { include_blank: true }, { class: "form-control" } %> 
        <% if @property.errors.has_key?(:status) %>
          <span class="field-error"><%= @property.errors.messages[:status].join(", ") %></span>
        <% end %>      
      </div>  

      <div class="form-group">
        <%= f.label :price, "Price" %><br>
        <%= f.text_field :price, class: "form-control" %>
        <% if @property.errors.has_key?(:price) %>
          <span class="field-error"><%= @property.errors.messages[:price].join(", ") %></span>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :street_number, "Street Number" %><br>
        <%= f.text_field :street_number, class: "form-control" %>
        <% if @property.errors.has_key?(:street_number) %>
          <span class="field-error"><%= @property.errors.messages[:street_number].join(", ") %></span>
        <% end %>
      </div>  

      <div class="form-group">
        <%= f.label :street_name, "Street Name" %><br>
        <%= f.text_field :street_name, class: "form-control" %>
        <% if @property.errors.has_key?(:street_name) %>
          <span class="field-error"><%= @property.errors.messages[:street_name].join(", ") %></span>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :suite, "Suite" %><br>
        <%= f.text_field :suite, class: "form-control" %>
        <% if @property.errors.has_key?(:suite) %>
          <span class="field-error"><%= @property.errors.messages[:suite].join(", ") %></span>
        <% end %>
      </div>      

      <div class="form-group">
        <%= f.label :city, "City" %><br>
        <%= f.text_field :city, class: "form-control" %>
        <% if @property.errors.has_key?(:city) %>
          <span class="field-error"><%= @property.errors.messages[:city].join(", ") %></span>
        <% end %>
      </div>   

      <div class="form-group">
        <%= f.label :state, "State" %><br>
        <%= f.collection_select :state_id, @states, :id, :name, { include_blank: true }, { class: "form-control" } %>    
        <% if @property.errors.has_key?(:state) %>
          <span class="field-error"><%= @property.errors.messages[:state].join(", ") %></span>
        <% end %>      
      </div>

      <div class="form-group">
        <%= f.label :zipcode, "Zipcode" %><br>
        <%= f.text_field :zipcode, class: "form-control" %>
        <% if @property.errors.has_key?(:zipcode) %>
          <span class="field-error"><%= @property.errors.messages[:zipcode].join(", ") %></span>
        <% end %>
      </div> 

      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>

  </div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Property Leads</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
          <% if @property.new_record? %>
            <% @disable_add_customer="disabled" %>
          <% else %>
            <% @disable_add_customer=nil %>
            <%= form_tag(add_customer_property_path(@property), method: :post) do %>
              <div class="form-group">
              <%= select_tag(:customer_id, options_for_select(@leads), include_blank: true, class: "form-control", id: "select-customer", disabled: @disable_add_customer) %> 
              </div>
              <div class="form-group">
              <%= submit_tag("Add customer", class: "btn btn-primary", disabled: "disabled", id: "btn-add-customer", "data-toggle": "tooltip", "data-placement": "bottom", title: "Select a customer to add it") %>
              </div> 
            <% end %>             
          <% end%>         
          </div>
        </div>      
        <table class="table">
          <% @customers.each do |c| %>
          <tr>
            <td><%= c[0]%></td>
            <td><%= link_to 'remove', remove_customer_property_path(@property, c[1]) %></td>
          </tr>
          <% end %>          
        </table>
      </div>
    </div>    
  </div>
</div>

app/views/properties/edit.html.erb
<%= render 'edit' %>

app/views/properties/index.html.erb
<!-- SEARCH BAR -->
<div class="row summary">
  <div class="col-md-12">
  <%= form_tag search_properties_path, method: "get" do %>
    <div class="form-group">
      <div class="input-group">
        <%= text_field_tag "search_criteria", flash[:search_criteria], placeholder: "street, number or description...", class: "form-control" %>
        <span class="input-group-btn">
        <%= button_tag type: "submit", class: "btn btn-default", id: "search_btn" do %>
          <span class="glyphicon glyphicon-search"></span> search
        <% end %>
        </span>
      </div>
    </div>
  <% end %>
  </div>   
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-responsive">
      <thead>
        <tr>
          <th class="text-center"></th>
          <th class="text-center">Title</th>
          <th class="text-center">Address</th>
          <th class="text-center">City</th>
          <th class="text-center">Price</th>
          <th class="text-center">Broker</th>
          <th class="text-center">Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @properties.each do |property| %>
          <tr>
            <td class="text-left">
            <% if property.photo %>
              <%= image_tag("/uploads/#{property.photo}", size: "48x48") %>
            <% else %>
              <%= image_tag("/uploads/no_photo.png", size: "48x48") %>              
            <% end %>
            </td>            
            <td class="text-left"><%= property.title %></td>
            <td class="text-left"><a href="#" class="map-link" data-toggle="modal" data-target="#maps-modal" data-address="<%= property.full_address %>"><%= property.address %></a></td>
            <td class="text-center"><%= property.location %></td>
            <td class="text-right"><%= number_to_currency(property.price, precision: 2) %></td>
            <td class="text-center"><%= property.agent.full_name %></td>
            <td class="text-center">
            <% if property.for_sale? %>
              <span class="label label-success"><%= property.status.humanize %></span>
            <% else %>
              <span class="label label-default"><%= property.status.humanize %></span>            
            <% end %>
            </td>            
            <td class="text-center"><%= link_to 'Details', property %></td>
            <td class="text-center"><%= link_to 'Edit', edit_property_path(property) %></td>
            <td class="text-center"><%= link_to 'Delete', property, method: :delete, data: { confirm: 'Are you sure you want to delete this property?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <span style="font-style: italic">Showing <strong><%= @current_record_count %></strong> records of <strong><%= @total_record_count %></strong></span>
  </div>
  <div class="col-md-4">
    <%= link_to 'New Property', new_property_path, class: "pull-right btn btn-primary" %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <nav>
      <ul class="pagination">
        <li class="disabled">
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <% 1.upto(@pages) do |page| %>
          <% if flash[:search_criteria] %>
            <li><%= link_to page, search_properties_path(search_criteria: flash[:search_criteria] , page: page) %></li>
          <% else %>
            <li><%= link_to page, page_properties_path(page) %></li>
          <% end %>
        <% end %>
        <li>
          <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>  
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="maps-modal" tabindex="-1" role="dialog" aria-labelledby="maps-modal-label">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="maps-modal-label">Address</h4>
      </div>
      <div class="modal-body">
         <iframe id="map-iframe" width="100%" height="400"></iframe> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/properties/my_properties.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-responsive">
      <thead>
        <tr>
          <th class="text-center"></th>
          <th class="text-center">Title</th>
          <th class="text-center">Address</th>
          <th class="text-center">City</th>
          <th class="text-center">Price</th>
          <th class="text-center">Broker</th>
          <th class="text-center">Status</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @my_properties.each do |property| %>
          <tr>
            <td class="text-left">
            <% if property.photo %>
              <%= image_tag("/uploads/#{property.photo}", size: "48x48") %>
            <% else %>
              <%= image_tag("/uploads/no_photo.png", size: "48x48") %>              
            <% end %>
            </td>            
            <td class="text-left"><%= property.title %></td>
            <td class="text-left"><a href="#" class="map-link" data-toggle="modal" data-target="#maps-modal" data-address="<%= property.full_address %>"><%= property.address %></a></td>
            <td class="text-center"><%= property.location %></td>
            <td class="text-right"><%= number_to_currency(property.price, precision: 2) %></td>
            <td class="text-center"><%= property.agent.full_name %></td>
            <td class="text-center">
            <% if property.for_sale? %>
              <span class="label label-success"><%= property.status.humanize %></span>
            <% else %>
              <span class="label label-default"><%= property.status.humanize %></span>            
            <% end %>
            </td>            
            <td class="text-center"><%= link_to 'Details', property %></td>
            <td class="text-center"><%= link_to 'Edit', edit_property_path(property) %></td>
            <td class="text-center"><%= link_to 'Delete', property, method: :delete, data: { confirm: 'Are you sure you want to delete this property?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="maps-modal" tabindex="-1" role="dialog" aria-labelledby="maps-modal-label">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="maps-modal-label">Address</h4>
      </div>
      <div class="modal-body">
         <iframe id="map-iframe" width="100%" height="400"></iframe> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/properties/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<%= render 'edit' %>