config/routes.rb
Rails.application.routes.draw do

  resources :properties do
    collection do 
      get 'search'
      get 'page/:page' => 'properties#paginate', as: :page
      get 'my_properties' => 'properties#my_properties', as: :my_properties
    end  
    member do
      post 'add_customer'
      get 'remove_customer/:customer_id' => 'properties#remove_customer', as: :remove_customer
    end
  end

  resources :agents do
    collection do 
      get 'search'
      get 'page/:page' => 'agents#paginate', as: :page
    end  
  end  

  resources :customers do
    collection do 
      get 'search'
      get 'page/:page' => 'customers#paginate', as: :page
    end  
  end  

  resources :states do
    collection do 
      get 'search'
      get 'page/:page' => 'states#paginate', as: :page
    end  
  end  

  resources :users do
    collection do 
      get 'search'
      get 'page/:page' => 'users#paginate', as: :page
    end  
  end  

  root 'sessions#index'

  get 'login' => 'sessions#index'
  get 'sessions/forgot_password'
  post 'sessions/create'
  delete 'sessions/destroy'
  get 'dashboard' => 'dashboard#index'

  get 'my_account', to: 'my_account#show'
  put 'my_account', to: 'my_account#update'
  patch 'my_account', to: 'my_account#update'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  has_many :customer_properties
  has_many :properties, through: :customer_properties
  accepts_nested_attributes_for :user, allow_destroy: true

  validates :mobile, presence: true
  validates :user, presence: true

  enum title: [:mr, :mrs, :ms]

  validates :title, presence: true

  def full_name
    "#{title}.humanize #{first_name} #{last_name}"
  end

  def self.paginate(page=1)
    page ||= 1

    # Set the pagination info on every data pull
    total_record_count = Customer.count
    pages  = (total_record_count.to_f / ENV['MAX_RECORDS_PER_PAGE'].to_f).ceil
    current_page = page

    max_records_per_page = ENV['MAX_RECORDS_PER_PAGE'].to_i
    current_offset = ((page.to_i*max_records_per_page))-max_records_per_page
    customers = Customer.limit(max_records_per_page).offset(current_offset)
    current_record_count = customers.try(:count)

    {
      current_page: page,
      pages: pages,
      max_records_per_page: max_records_per_page,
      current_offset: current_offset,
      current_record_count: current_record_count,
      total_record_count: total_record_count,
      records: customers

    }
  end

  def self.search(search_criteria, page=1)
    page ||= 1

    # Set the pagination info on every data pull
    total_record_count = Customer.joins(:user).where(" users.first_name LIKE LOWER('%#{search_criteria}%') OR users.last_name LIKE LOWER('%#{search_criteria}%') OR users.email LIKE LOWER('%#{search_criteria}%') ").count
    pages  = (total_record_count.to_f / ENV['MAX_RECORDS_PER_PAGE'].to_f).ceil
    current_page = page

    max_records_per_page = ENV['MAX_RECORDS_PER_PAGE'].to_i
    current_offset = ((page.to_i*max_records_per_page))-max_records_per_page
    customers = Customer.joins(:user).where(" users.first_name LIKE LOWER('%#{search_criteria}%') OR users.last_name LIKE LOWER('%#{search_criteria}%') OR users.email LIKE LOWER('%#{search_criteria}%') ").limit(max_records_per_page).offset(current_offset)
    current_record_count = customers.try(:count)

    {
      current_page: page,
      pages: pages,
      max_records_per_page: max_records_per_page,
      current_offset: current_offset,
      current_record_count: current_record_count,
      total_record_count: total_record_count,
      records: customers
    }
  end 

  def self.to_csv
    attributes = %w{id title phone mobile user_id created_at updated_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |customer|
        csv << attributes.map{ |attr| customer.send(attr) }
      end
    end
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @page_title = "Customers List"
    customer_data = Customer::paginate
    set_pagination(customer_data)

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @customers, status: :ok }
      format.csv { send_data Customer.to_csv, filename: "customers-#{Date.today}.csv" }
      format.pdf do
        pdf = Prawn::Document.new
        pdf.text(Customer.to_csv)
        pdf.render_file(Rails.root.join('tmp', "customers-#{Date.today}.pdf"))
        send_file Rails.root.join('tmp', "customers-#{Date.today}.pdf")
      end      
    end    
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @page_title = "Customer Details"
  end

  # GET /customers/new
  def new
    @page_title = "New Customer"
    @customer = Customer.new
    @customer.build_user
  end

  # GET /customers/1/edit
  def edit
    @page_title = "Edit Customer"
  end

  # POST /customers
  # POST /customers.json
  def create
    @page_title = "New Customer"
    @customer = Customer.new(customer_params)
    @customer.user.status = User.statuses[:active]
    @customer.user.role = User.roles[:customer]

    respond_to do |format|
      if @customer.save
        flash[:type] = FLASH_TYPES[:success]
        flash[:msg] = "Customer successfully created"          
        format.html { redirect_to @customer}
        format.json { render :show, status: :created, location: @state }
      else
        flash.now[:type] = FLASH_TYPES[:warning]
        flash.now[:msg] = "Please fill in all required information"         
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        flash[:type] = FLASH_TYPES[:success]
        flash[:msg] = "Customer successfully updated"        
        format.html { redirect_to @customer }
        format.json { render :show, status: :ok, location: @state }
      else
        flash.now[:type] = FLASH_TYPES[:warning]
        flash.now[:msg] = "Please fill in all required information"             
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    if @customer.destroy
      respond_to do |format|
        flash.now[:type] = FLASH_TYPES[:success]
        flash.now[:msg] = "Customer successfully deleted"
        format.html { redirect_to customers_url }
        format.json { head :no_content }
      end
    else
        flash.now[:type] = FLASH_TYPES[:warning]
        flash.now[:msg] = "There was a problem trying to delete the customer"     
        format.html { render :index }
        format.json { render json: @customer.errors, status: :unprocessable_entity }      
    end
  end

  def search 
    current_page = params[:page]
    search_criteria = params[:search_criteria]
    customer_data = Customer.search(search_criteria, current_page)
    set_pagination(customer_data)
    flash.now[:search_criteria] = params[:search_criteria]

    if customer_data[:total_record_count] > 0
      flash.now[:type] = FLASH_TYPES[:info]
      flash.now[:msg] = "#{customer_data[:total_record_count]} results found"
    else
      flash.now[:type] = FLASH_TYPES[:warning]
      flash.now[:msg] = "No records found matching your criteria"
    end


    respond_to  do |format| 
      format.html { render :index }
      format.json { head :no_content }
    end
  end

  def paginate
    current_page = params[:page]
    customer_data = Customer.paginate(current_page)
    set_pagination(customer_data)

    respond_to  do |format| 
      format.html { render :index }
      format.json { head :no_content }
    end   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:title, :phone, :mobile, :user_id, user_attributes: [:id, :first_name, :last_name, :email, :password])
    end

    def set_pagination(customer_data)
      @customers = customer_data[:records]
      @total_record_count = customer_data[:total_record_count]
      @pages = customer_data[:pages]
      @current_record_count = customer_data[:current_record_count]
    end     
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_edit.html.erb
<%= render 'form' %>

<%= link_to "Back", customers_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>

  <div class="form-group">
    <%= f.label :title, "Title" %><br>
    <%= f.select :title, Customer.titles.to_a.map { |t| [t[0].humanize, t[0]] }, { include_blank: true }, { class: "form-control" } %> 
    <% if @customer.errors.has_key?(:title) %>
      <span class="field-error"><%= @customer.errors.messages[:title].join(", ") %></span>
    <% end %>      
  </div> 

  <%= f.fields_for :user do |u| %>
    <div class="form-group">
      <%= u.label :first_name, "First Name" %><br>
      <%= u.text_field :first_name, class: "form-control" %>
      <% if @customer.user.errors.has_key?(:first_name) %>
        <span class="field-error"><%= @customer.user.errors.messages[:first_name].join(", ") %></span>
      <% end %>
    </div>

    <div class="form-group">
      <%= u.label :last_name, "Last Name" %><br>
      <%= u.text_field :last_name, class: "form-control" %>
      <% if @customer.user.errors.has_key?(:last_name) %>
        <span class="field-error"><%= @customer.user.errors.messages[:last_name].join(", ") %></span>
      <% end %>
    </div>    

    <div class="form-group">
      <%= u.label :email, "E-Mail" %><br>
      <%= u.text_field :email, class: "form-control", type: "email" %>
      <% if @customer.user.errors.has_key?(:email) %>
        <span class="field-error"><%= @customer.user.errors.messages[:email].join(", ") %></span>
      <% end %>
    </div>

    <div class="form-group">
      <%= u.label :password, "Password" %><br>
      <%= u.text_field :password, class: "form-control", type: "password" %>
      <% if @customer.user.errors.has_key?(:password) %>
        <span class="field-error"><%= @customer.user.errors.messages[:password].join(", ") %></span>
      <% end %>
    </div>
    
  <% end %>

  <div class="form-group">
    <%= f.label :mobile, "Mobile" %><br>
    <%= f.text_field :mobile, class: "form-control" %>
    <% if @customer.errors.has_key?(:mobile) %>
      <span class="field-error"><%= @customer.errors.messages[:mobile].join(", ") %></span>
    <% end %>
  </div> 

  <div class="form-group">
    <%= f.label :phone, "Phone" %><br>
    <%= f.text_field :phone, class: "form-control" %>
    <% if @customer.errors.has_key?(:phone) %>
      <span class="field-error"><%= @customer.errors.messages[:phone].join(", ") %></span>
    <% end %>
  </div> 
 
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<!-- SEARCH BAR -->
<div class="row summary">
  <div class="col-md-12">
  <%= form_tag search_customers_path, method: "get" do %>
    <div class="form-group">
      <div class="input-group">
        <%= text_field_tag "search_criteria", flash[:search_criteria], placeholder: "first name, last name or email...", class: "form-control" %>
        <span class="input-group-btn">
        <%= button_tag type: "submit", class: "btn btn-default", id: "search_btn"  do %>
          <span class="glyphicon glyphicon-search"></span> search
        <% end %>
        </span>
      </div>
    </div>
  <% end %>
  </div>   
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover table-bordered table-responsive">
      <thead>
        <tr>
          <th class="text-center">Name</th>
          <th class="text-center">Phone</th>
          <th class="text-center">Mobile</th>
          <th class="text-center">E-Mail</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td class="text-left"><%= customer.user.full_name %></td>
            <td class="text-center"><%= customer.phone %></td>
            <td class="text-center"><%= customer.mobile %></td>
            <td class="text-center"><%= customer.user.email %></td>
            <td class="text-center"><%= link_to 'Details', customer %></td>
            <td class="text-center"><%= link_to 'Edit', edit_customer_path(customer) %></td>
            <td class="text-center"><%= link_to 'Delete', customer, method: :delete, data: { confirm: 'Are you sure you want to delete this customer?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <span style="font-style: italic">Showing <strong><%= @current_record_count %></strong> records of <strong><%= @total_record_count %></strong></span>
  </div>
  <div class="col-md-4">
    <%= link_to 'New Customer', new_customer_path, class: "pull-right btn btn-primary" %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <nav>
      <ul class="pagination">
        <li class="disabled">
          <a href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <% 1.upto(@pages) do |page| %>
          <% if flash[:search_criteria] %>
            <li><%= link_to page, search_customers_path(search_criteria: flash[:search_criteria] , page: page) %></li>
          <% else %>
            <li><%= link_to page, page_customers_path(page) %></li>
          <% end %>
        <% end %>
        <li>
          <a href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>  
  </div>
</div>

app/views/customers/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', agents_path %>

app/views/customers/show.html.erb
<%= render 'edit' %>